image: maven:3.8-openjdk-11
default:
  tags:
    - "shellocal"
cache:
  paths:
    - .m2/repository
    - target/

stages:
  - "test"
  - "allure-report"

test:
  stage: test
  script:
    - mvn clean test

allure:
  stage: allure-report
  script:
    - mvn io.qameta.allure:allure-maven:report
    - mvn io.qameta.allure:allure-maven:serve target/allure-results
  artifacts:
    paths:
      - allure-report/
  when: always
