image: my-custom-chrome

cache:
  paths:
    - m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn clean test
  only:
    - triggers

allure:
  stage: allure-report
  script:
    - apt update && apt install -y allure
    - mvn io.qameta.allure:allure-maven:report
    - mvn io.qameta.allure:allure-maven:serve target/allure-results
  artifacts:
    paths:
      - allure-report/