image: maven:latest

cache:
  paths:
    - m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn clean test

deploy:
  stage: deploy
  script:
    - io.qameta.allure:allure-maven:report

