image: selenium/standalone-chrome:latest

cache:
  paths:
    - m2/repository/
    - target/

test:
  stage: test
  script:
    - google-chrome --version
    - mvn io.qameta.allure:allure-maven:report
    - mvn clean test

