image: maven:latest

cache:
  paths:
    - m2/repository/
    - target/

test:
  stage: test
  script:
    - google-chrome --version || chromium-browser --version || echo "Browser not found"
    - mvn io.qameta.allure:allure-maven:report
    - mvn clean test

