stages:
  - "test"
  - "allure-report"
  - "docker"
cache:
  paths:
    - .m2/repository
    - target/
docker:
  image: registry.webdevsrv.office.aisa.ru/maksim.riabtsev/wabp_test/my-custom-chrome
  stage: docker
  script:
    - chmod +x ./mvnw
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

test:
  stage: test
  script:
    - mvn clean test


allure:
  stage: allure-report
  script:
    - apt update && apt install -y allure
    - mvn io.qameta.allure:allure-maven:report
    - mvn io.qameta.allure:allure-maven:serve target/allure-results
  artifacts:
    paths:
      - allure-report/
